/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.
// prettier-ignore
const awsmobile = {
    "aws_project_region": "ap-southeast-1",
    "aws_appsync_graphqlEndpoint": "https://192.168.56.1:20002/graphql",
    "aws_appsync_region": "ap-southeast-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-fakeApiId123456",
    "aws_cognito_identity_pool_id": "ap-southeast-1:11ea41a8-04f0-4f07-8230-652fd9806150",
    "aws_cognito_region": "ap-southeast-1",
    "aws_user_pools_id": "ap-southeast-1_M0sO9bsZq",
    "aws_user_pools_web_client_id": "37hei6rs4s18stghe0l74p6i2i",
    "oauth": {}
};

export default awsmobile;
