/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_appsync_graphqlEndpoint": "http://192.168.56.1:20002/graphql",
    "aws_appsync_region": "eu-central-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-fakeApiId123456",
    "aws_appsync_dangerously_connect_to_http_endpoint_for_testing": true,
    "aws_cognito_identity_pool_id": "eu-central-1:ba5ccece-61b6-4d47-b33b-2413ad5b9a40",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_MmVLErvqw",
    "aws_user_pools_web_client_id": "33ld5tdiileipgq4nq5j22uul8",
    "oauth": {}
};


export default awsmobile;
